# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equacoes.ui'
#
# Created: Wed Aug 12 20:56:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(425, 454)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.groupBox_7)
        self.Estado = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Estado.sizePolicy().hasHeightForWidth())
        self.Estado.setSizePolicy(sizePolicy)
        self.Estado.setMinimumSize(QtCore.QSize(100, 0))
        self.Estado.setMaximumSize(QtCore.QSize(0, 16777215))
        self.Estado.setBaseSize(QtCore.QSize(0, 0))
        self.Estado.setObjectName(_fromUtf8("Estado"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Estado)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBox_8)
        self.City = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.City.sizePolicy().hasHeightForWidth())
        self.City.setSizePolicy(sizePolicy)
        self.City.setMinimumSize(QtCore.QSize(100, 0))
        self.City.setMaximumSize(QtCore.QSize(0, 16777215))
        self.City.setObjectName(_fromUtf8("City"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.City)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.groupBox_2)
        self.m = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m.sizePolicy().hasHeightForWidth())
        self.m.setSizePolicy(sizePolicy)
        self.m.setDecimals(6)
        self.m.setMaximum(1000000000.0)
        self.m.setObjectName(_fromUtf8("m"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.m)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.groupBox_3)
        self.t0 = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t0.sizePolicy().hasHeightForWidth())
        self.t0.setSizePolicy(sizePolicy)
        self.t0.setDecimals(6)
        self.t0.setMaximum(1000000000.0)
        self.t0.setObjectName(_fromUtf8("t0"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.t0)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.groupBox_4)
        self.n = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n.sizePolicy().hasHeightForWidth())
        self.n.setSizePolicy(sizePolicy)
        self.n.setDecimals(6)
        self.n.setMaximum(1000000000.0)
        self.n.setObjectName(_fromUtf8("n"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.n)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.groupBox_5)
        self.Tr = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tr.sizePolicy().hasHeightForWidth())
        self.Tr.setSizePolicy(sizePolicy)
        self.Tr.setMaximum(2147483640)
        self.Tr.setObjectName(_fromUtf8("Tr"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.Tr)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.groupBox_6)
        self.t = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t.sizePolicy().hasHeightForWidth())
        self.t.setSizePolicy(sizePolicy)
        self.t.setMaximum(2147483640)
        self.t.setSingleStep(30)
        self.t.setObjectName(_fromUtf8("t"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.t)
        self.k = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k.sizePolicy().hasHeightForWidth())
        self.k.setSizePolicy(sizePolicy)
        self.k.setDecimals(6)
        self.k.setMaximum(1000000000.0)
        self.k.setObjectName(_fromUtf8("k"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.k)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.CalculaIDF = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalculaIDF.sizePolicy().hasHeightForWidth())
        self.CalculaIDF.setSizePolicy(sizePolicy)
        self.CalculaIDF.setAutoFillBackground(False)
        self.CalculaIDF.setObjectName(_fromUtf8("CalculaIDF"))
        self.horizontalLayout_3.addWidget(self.CalculaIDF)
        self.scs = QtGui.QPushButton(self.tab)
        self.scs.setObjectName(_fromUtf8("scs"))
        self.horizontalLayout_3.addWidget(self.scs)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.kirpich1 = QtGui.QRadioButton(self.tab_2)
        self.kirpich1.setObjectName(_fromUtf8("kirpich1"))
        self.verticalLayout_5.addWidget(self.kirpich1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.kirpich2 = QtGui.QRadioButton(self.tab_2)
        self.kirpich2.setObjectName(_fromUtf8("kirpich2"))
        self.verticalLayout_5.addWidget(self.kirpich2)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.kerby = QtGui.QRadioButton(self.tab_2)
        self.kerby.setObjectName(_fromUtf8("kerby"))
        self.verticalLayout_5.addWidget(self.kerby)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.bransby = QtGui.QRadioButton(self.tab_2)
        self.bransby.setObjectName(_fromUtf8("bransby"))
        self.verticalLayout_5.addWidget(self.bransby)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sair = QtGui.QPushButton(Dialog)
        self.sair.setObjectName(_fromUtf8("sair"))
        self.verticalLayout.addWidget(self.sair)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.sair, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Equacaoes", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Estado:", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Cidade:", None))
        self.groupBox.setTitle(_translate("Dialog", "K:", None))
        self.groupBox_2.setTitle(_translate("Dialog", "m:", None))
        self.groupBox_3.setTitle(_translate("Dialog", "t0:", None))
        self.groupBox_4.setTitle(_translate("Dialog", "n:", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Tr (anos):", None))
        self.groupBox_6.setTitle(_translate("Dialog", "t (minutos):", None))
        self.CalculaIDF.setText(_translate("Dialog", "Calcula IDF", None))
        self.scs.setText(_translate("Dialog", "Metodo SCS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "IDF", None))
        self.label_2.setText(_translate("Dialog", "Metodos:", None))
        self.label.setText(_translate("Dialog", "Tempo de Concentracao", None))
        self.kirpich1.setText(_translate("Dialog", "Kirpich I", None))
        self.label_3.setText(_translate("Dialog", "Lt - comprimento do talvegue, em m \n"
"h - diferenca de cotas, em m", None))
        self.kirpich2.setText(_translate("Dialog", "Kirpich II", None))
        self.label_4.setText(_translate("Dialog", "Lt - comprimento do talvegue, em m \n"
"St - declividade equivalente do talvegue, em m/km", None))
        self.kerby.setText(_translate("Dialog", "Kerby", None))
        self.label_5.setText(_translate("Dialog", "r- rugosidade do retardo \n"
"Lt - comprimento do talvegue, em m \n"
"St - declividade equivalente do talvegue, em m/km", None))
        self.bransby.setText(_translate("Dialog", "Bransby - Willians", None))
        self.label_6.setText(_translate("Dialog", "A - area da bacia ,em km2\n"
"St - declividade equivalente do talvegue, em m/km", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Dados da Bacia", None))
        self.sair.setText(_translate("Dialog", "Sair", None))

